#====================================================================
#	          █  Plugin: creft endercheast              █
#	          █  Made by : Zabujca997                   █
#	          █  Version : 1.0                          █
#			  █  Ts3     : ExtremeGames.gclan.pl        █
#====================================================================
# Copyright © 2017 Text Skripts Zabujca997 ExtremeGames. All rights reserved.
#====================================================================
on script load:
    register new shaped recipe for ender chest using obsidian, obsidian, obsidian, obsidian, ender pearl, obsidian, obsidian, obsidian, obsidian